# This references a standard debian container from the
# Docker Hub https://registry.hub.docker.com/_/debian/
# Read more about containers on our dev center
# http://devcenter.wercker.com/docs/containers/index.html
box: 3scale/openresty
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
# services:
# - postgres
# http://devcenter.wercker.com/docs/services/postgresql.html

# - mongodb
# http://devcenter.wercker.com/docs/services/mongodb.html

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
  # Steps make up the actions in your pipeline
  # Read more about steps on our dev center:
  # http://devcenter.wercker.com/docs/steps/index.html
  steps:
    - script:
      name: install dependencies
      code: |
        apt-get -yqq update
        apt-get install -yqq python python-pip
        pip install mkdocs
    - script:
      name: install module
      code: |
        luarocks make
    - script:
      name: integration test
      code: |
        ./docroc src docs --index README.md --config mkdocs.yml --github_src_dir http://github.com/vzhong/docroc/blob/master/src/ 
        mkdocs build --clean
        touch site/.nojekyll
deploy:
  steps:
    - script:
      name: install dependencies
      code: |
        apt-get -yqq update
        apt-get install -yqq git
    - lukevivier/gh-pages@0.2.1:
      token: $GIT_TOKEN
      basedir: site
