#!/usr/bin/env lua

local lapp = require 'pl.lapp'
local opt = lapp [[
Generate documentations recursively for a directory.
  <src_dir> (string) Source directory
  <doc_dir> (string) Documentation directory
  --config  (string) Mkdocs config file. If specified, then pages will be appended to the config file.
  --index (default '')  File to use to create homepage.
  --github_src_dir (default '')  URL to the source blob directory on github.
]]

local path = require 'pl.path'
local dir = require 'pl.dir'
local file = require 'pl.file'
local yaml = require 'yaml'

for k, v in pairs(opt) do
  if v == '' then opt[k] = nil end
end

local pages = {}

local writer = require 'docroc.writer'
writer.process_dir(opt.src_dir, opt.doc_dir, opt.github_src_dir)

local name2category = {}

for root, dirs, files in dir.walk(opt.doc_dir) do
  for _, fname in ipairs(files) do
    local name, ext = path.splitext(fname)
    if ext == '.md' then
      local fpath = path.join(root, fname):gsub(opt.doc_dir..'/', '')
      local dirname, _ = path.splitpath(fpath)
      if not name2category[dirname] and dirname ~= '' then
        local entry = {}
        entry[dirname] = {}
        table.insert(pages, entry)
        name2category[dirname] = pages[#pages][dirname]
      end
      local entry = {}
      entry[name] = fpath
      if dirname == '' then
        if name ~= 'index' then
          table.insert(pages, entry)
        end
      else
        table.insert(name2category[dirname], entry)
      end
    end
  end
end

-- copy readme
if path.exists(opt.index) then
  file.copy(opt.index, path.join(opt.doc_dir, 'index.md'))
end
table.insert(pages, 1, {Home='index.md'})

if opt.config then
  local config = yaml.load(file.read(opt.config))
  local content = yaml.dump{pages=pages}
  -- this hack is for mkdocs weirdness
  content = content:gsub('%- (%w+): ([^\n]+)', function(a, b)
    return "- '"..a.."': '"..b.."'"
  end)
  config.pages = nil
  content = yaml.dump(config) .. content
  content = content:gsub('[^\n]%-+\n', '')
  print(content)
  file.write('mkdocs.yml', content)
end
